- name: "Install official outline font packages"
  block:
    - name: "Install 'Liberation' outline font"
      ansible.builtin.package:
        name: fonts-liberation2
        state: present
      when: install_liberation_font
    - name: "Install 'DejaVu' outline font"
      ansible.builtin.package:
        name: fonts-dejavu
        state: present
      when: install_dejavu_font
    - name: "Install 'GNU FreeFont' outline font"
      ansible.builtin.package:
        name: fonts-freefont-ttf
        state: present
      when: install_gnu_freefont_font
    - name: "Install 'Libertinus' outline font"
      ansible.builtin.package:
        name: fonts-linuxlibertine
        state: present
      when: install_libertinus_font
    - name: "Install Microsoft outline fonts"
      ansible.builtin.package:
        name: ttf-mscorefonts-installer
        state: present
      when: (install_ms_legacy_fonts or install_ms_vista_fonts)
  become: true
  become_user: root

